# Generated by Django 4.2.7 on 2025-01-09 23:04

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_deliverycouriers_url_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusers',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponusers',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='applied_coupon',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='default_images/product.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponUsers',
        ),
    ]
